Shuffled deck and matching functionality
khaletska/Set pull request #2
Opened 2024-06-12 13:14 UTC by khaletska

1. Game starts with shuffled deck of 81 different cards
2. Implemented matching function

2024-06-12 13:42 UTC, Shiaulis requested changes
nice progress 🥇 
we just need to adjust some responsibilities and ensure we are using efficient matching logic

2024-06-12 13:42 UTC, Shiaulis commented on Set/Deck.swift
> +    }()
the implementation is fine, but can we make this function part of business logic e.g. Game class?

2024-06-12 13:42 UTC, Shiaulis commented on Set/Deck.swift
> +struct Deck {
why do we need this struct? Seems it is just an array of cards 🤔

2024-06-12 13:42 UTC, Shiaulis commented on Set/Set/Card.swift
> +        self.content = NSAttributedString(string: string, attributes: attributes)
I assume this file with inclusion of UIKit violates this statement from requirements
```
NSAttributedStringKeys like foregroundColor are not appropriate for use in a Model (note that a color is a UIColor, which means it’s a UI thing). Do not use NSAttributedStrings in your Model.
```

2024-06-12 13:42 UTC, Shiaulis commented on Set/Set/Card.swift
> +enum Color: CaseIterable {
I would prefer to make there enums within Card namespace. It would be more cautious to call `Card.Color` instead of just `Color`

2024-06-12 13:42 UTC, Shiaulis commented on Set/Set/SetGame.swift
> +        self.deck = Deck().deck
If I don't know the implementation of this line I don't understand what it does. It reads like `deck equals to deck deck`. This is why it makes sense to consider some more meaningful naming or get rid of Deck entity at all

2024-06-12 13:42 UTC, Shiaulis commented on Set/Set/SetGame.swift
> +        let card1 = self.shownCards[chosenCardsIndices[0]]
is it possible to make this logic independent from amount of matching cards? 🤔

2024-06-12 13:42 UTC, Shiaulis commented on Set/Set/SetGame.swift
> +    private func isMatching<T: Equatable>(_ a: T, _ b: T, _ c: T) -> Bool {
like this idea 🚀
can it compare any count of elements?

2024-06-12 18:12 UTC, khaletska commented on Set/Set/Card.swift
> +        self.content = NSAttributedString(string: string, attributes: attributes)
No way 😭
Okay, this is what I might need help on

2024-06-13 13:14 UTC, Shiaulis approved these changes

2024-06-13 13:14 UTC, Shiaulis commented on Set/Set/Card.swift
> +    let number: Card.Number
Since we are inside of `Card` context it is fine to omit this. But, if you feel you benefit from them then surely leave it as it is right now
```suggestion
    let color: Color
    let shade: Shade
    let shape: Shape
    let number: Number
```

2024-06-13 13:16 UTC, merged