Implement Grid
khaletska/Set pull request #7
Opened 2024-06-27 10:42 UTC by khaletska

- Added usage of Grid for dynamically aligning cards on the screen
- Deal more cards button works until the end of the deck
- Made a HUGE mess 😢

2024-06-27 10:52 UTC, khaletska commented
Found a bug: If the match id chosen and highlighted, next chosen card disappears too (if the deck is empty)

2024-06-27 11:19 UTC, Shiaulis commented
> Found a bug: If the match id chosen and highlighted, next chosen card disappears too (if the deck is empty)

does it mean you are going to fix it?

2024-06-28 09:43 UTC, khaletska commented
> > Found a bug: If the match id chosen and highlighted, next chosen card disappears too (if the deck is empty)
> 
> does it mean you are going to fix it?

Fixed

2024-06-28 10:51 UTC, Shiaulis requested changes
left some comments.
Make sure to review your own code in Github before requesting review from others. It is the easiest way to spot such issues that unnecessary commented code or some typos

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/Controller/ViewController.swift
> +//        if (self.game.shownCards.compactMap { $0 }[index] != nil) {
let's remove all commented code 🙏🏾

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/View/GridView.swift
> +            let cardButtonView = CardButton(frame: frame)
if cardButton is based on on card it makes sense to pass card within init and setup button based on the card itself

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/Model/SetGame.swift
> +        guard let ID = getCardID(by: indexOnBoard) else {
```suggestion
        guard let id = getCardID(by: indexOnBoard) else {
```

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/Model/SetGame.swift
> +        guard let ID = getCardID(by: indexOnBoard) else {
```suggestion
        guard let id = getCardID(by: indexOnBoard) else {
```

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/Model/SetGame.swift
>      private var unmatchedCardsIndices: Array<Int> = []
i assume it is not indices but IDs?

2024-06-28 10:51 UTC, Shiaulis commented on Set/Set/Model/SetGame.swift
> +        return deck//.shuffled()
i would prefer deck to be shuffled

2024-06-28 11:07 UTC, khaletska commented
> such issues that unnecessary commented code or some typos
sorry about this

2024-06-28 11:15 UTC, khaletska commented on Set/Set/Model/SetGame.swift
> +        return deck//.shuffled()
☢️

2024-06-28 12:29 UTC, Shiaulis approved these changes
left comment regarding future usage of `Identifiable`.
Another comment (no need to fix it) is that we should not limit size of a button if it has potential to grow. With current constraints but with bigger font current layout becomes broken 

![image](https://github.com/khaletska/Set/assets/13601748/ddff3a2e-c146-4c31-a2a4-1a3d9b4463ea)

![image](https://github.com/khaletska/Set/assets/13601748/18352beb-3fbd-49b2-95d1-399a62ed7ffa)

2024-06-28 12:29 UTC, Shiaulis commented on Set/Set/Controller/Card.swift
> +    let id: Int
In future I would recommend you to use `Identifiable` protocol and access object ID  type by `Card.ID` to abstract its implementation

2024-06-28 12:34 UTC, merged